include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - windows/flutter/ephemeral/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
